# Generated by Django 5.2.8 on 2025-11-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'managed': True},
        ),
    ]
