# Generated by Django 5.2.8 on 2025-11-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(blank=True, db_column='movieid', null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='userId',
            field=models.IntegerField(db_column='userid'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('userId', 'movie')},
        ),
    ]
